version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: springauthdatabase
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    ports:
#      - "5432:5432"
    volumes:
      - postgres_securitydata:/var/lib/postgresql/data
    networks:
      - postgres_network

  springsecurityjjwt-api:
    image: springsecurityjjwt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      HOST: postgres  
      DB_PORT: 5432
    depends_on:
      - postgres
    networks:
      - postgres_network

volumes:
  postgres_securitydata:

networks:
  postgres_network:
    driver: bridge
